appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'
urlpatterns = [
    path('make-appintment', views.MakeAppointment.as_view(), name='make-appintment'),
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.Blog.as_view (), name='blogs'),
    path('detail/<int:pk>', views.BlogDetail.as_view (), name='blog_detail'),
]

dental_appointment/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('appintment/', include('appointment.urls')),
    path('doctor/', include('doctor.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('account.urls')),
    path('rating/', include('rating.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path, include
from . import views

app_name = 'doctor'
urlpatterns = [
    path('search-doctor', views.SearchDoctor.as_view(), name='search-doctor'),
    path('service-price', views.ServicesAndPrices.as_view(), name='service-price'),
    path('doctors-certificate', views.DoctorsCertificate.as_view(), name='doctors-certificate'),
    path('our-team', views.Team.as_view(), name='our-team'),
    path('doctor-detail/<int:pk>/', views.doctor_detail, name='doctor-detail'),
]

doctor/models.py
from django.db import models
from about.models import Day
from django.utils.text import slugify

class DentalExperts(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=500, unique=True)
    cost = models.FloatField()
    image = models.ImageField(upload_to='services', null=True)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Service, self).save()

# Create your models here.
class Doctor(models.Model):
    name = models.CharField(max_length=500)
    last_name = models.CharField(max_length=500)
    expert = models.ForeignKey(DentalExperts, on_delete=models.CASCADE, related_name='doctors_expert')
    instagram = models.CharField(max_length=500)
    telegram = models.CharField(max_length=500)
    linkedin = models.CharField(max_length=500)
    img = models.ImageField(upload_to='doctors', default='/doctors/team-1.jpg')
    service = models.ManyToManyField(Service, related_name='doctors')
    day = models.ManyToManyField(Day, related_name='day_work')
    in_time = models.TimeField()
    out_time = models.TimeField()

    def __str__(self):
        return f'{self.name} - {self.last_name}'


class Certificate(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='certificate')
    image = models.ImageField(upload_to='certificate')
    explanation = models.TextField()

    def __str__(self):
        return self.explanation

doctor/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, DetailView
import datetime
from . import models


class SearchDoctor(View):
    def get(self, request):
        request = self.request
        date = datetime.datetime.strptime(request.GET.get('date'), '%m/%d/%Y')
        service = request.GET.get('service')
        doctors = models.Doctor.objects.filter(service__name=service, day__day=date.strftime('%A'))
        return render(request, 'doctor/search_doctor.html', {'doctors': doctors})


class ServicesAndPrices(View):
    def get(self, request):
        return render(request, 'doctor/service_price.html', {'service': models.Service.objects.all()})


class DoctorsCertificate(TemplateView):
    template_name = 'doctor/certificates.html'


class Team(TemplateView):
    template_name = 'doctor/teams.html'


def doctor_detail(request, pk):
    doctor = models.Doctor.objects.get(id=pk)
    return render(request, 'doctor/doctor-detail.html', {'doctor': doctor})

doctor/templates/doctor/certificates.html
{% extends 'base.html' %}
{% load static %}

{% block title %}doctor's certificate{% endblock %}

{% block content %}
    <!-- Testimonial Start -->
    <div class="container-fluid bg-primary bg-testimonial py-5 my-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="section-title mb-4">
                <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Certificate</h5>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="owl-carousel testimonial-carousel rounded p-5 wow zoomIn" data-wow-delay="0.6s">
                    {{ certificatess }}
                        {% for cer in certificates %}
                            <div class="testimonial-item text-center text-white">
                                <img class="img-fluid mx-auto rounded mb-4" src="{{ cer.doctor.img.url }}"
                                     alt="">
                                <p class="fs-5">{{ cer.explanation }}</p>
                                <hr class="mx-auto w-25">
                                <h4 class="text-white mb-0">{{ cer.doctor.name }} - {{ cer.doctor.last_name }}
                                    <a href="{{ cer.image.url }}" class="border border-white">
                                    <span class="m-1">
                                        <svg color="white"
                                             xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                             fill="currentColor"
                                             class="bi bi-eye" viewBox="0 0 16 16">
                                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                        </svg>
                                    </span>
                                    </a></h4>

                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Testimonial End -->
{% endblock %}

doctor/templates/doctor/doctor-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}dr. {{ doctor.name }}-{{ doctor.last_name }}{% endblock %}

{% block content %}
    <!-- Detail Start -->
    <div class="container-fluid bg-primary bg-testimonial py-5 my-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-7 bg-light">

                    <div class="testimonial-item text-center text-white">
                        <img class="img-fluid mx-auto rounded-5 m-4 w-25" src="{{ doctor.img.url }}"
                             alt="">
                        <p class="fs-5 text-primary">
                        <h4>doctor full name</h4>
                        <span class="text-primary"> {{ doctor.name }} - {{ doctor.last_name }}</span>
                        </p>
                        <p>
                        <h4>services</h4>

                        {% for ser in doctor.service.all %}
                            {% if forloop.last %}
                                <span class="text-primary">
                                {{ ser }}
                                </span>
                            {% else %}
                                <span class="text-primary">
                                {{ ser }} -
                                </span>
                            {% endif %}
                        {% endfor %}
                        </p>
                        <p>
                        <h4>expert</h4>
                        <span class="text-primary">{{ doctor.expert }}</span>
                        </p>
                        <p>
                        <h4>in time - out time</h4>
                        <span class="text-primary">{{ doctor.in_time }} - {{ doctor.out_time }}</span>
                        </p>
                        <p>
                            {% if request.user.is_authenticated %}
                                <!-- star rating -->
                                <form class="rate_form" method="post" action="" id="{{ doctor.id }}">
                                    {% csrf_token %}
                                    <fieldset class="border border-primary ">
                                        <h4>
                                            <legend class="text-dark m-2">Rating:</legend>
                                        </h4>

                                        <!-- star rating -->
                                        <div class="text-dark">
                                            <button type="submit" class="fa fa-star border border-light bg-light"
                                                    id="first"></button>
                                            <button type="submit" class="fa fa-star border border-light bg-light"
                                                    id="second"></button>
                                            <button type="submit" class="fa fa-star border border-light bg-light"
                                                    id="third"></button>
                                            <button type="submit" class="fa fa-star border border-light bg-light"
                                                    id="fourth"></button>
                                            <button type="submit" class="fa fa-star border border-light bg-light"
                                                    id="fifth"></button>
                                        </div>
                                        <div id="confirm-box"></div>
                                        <!-- star rating end-->
                                        </fildset>
                                        <!-- star rating end-->
                                        </p>
                                    </fieldset>
                                </form>
                            {% endif %}
                    </div>
                </div>
            </div>


        </div>

    </div>
    <script src="{% static 'js/rating.js' %}"></script>

    <!-- Detail End -->
{% endblock %}

doctor/templates/doctor/search_doctor.html
{% extends 'base.html' %}
{% load handel_delay %}
{% block title %}search doctor{% endblock %}

{% block content %}
    <div class="container-fluid py-5">
        <div class="container">
            {% if doctors %}

                <div class="row g-5">
                    <div class="col-lg-4 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title bg-light rounded h-100 p-5">
                            <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Dentist</h5>
                            <h1 class="display-6 mb-4">Meet Our Certified & Experienced Dentist</h1>
                            <a href="{% url 'appointment:make-appintment' %}"
                               class="btn btn-primary py-3 px-5">Appointment</a>
                        </div>
                    </div>
                    {% for dr in doctors %}
                        <div class="col-lg-4 wow slideInUp" data-wow-delay="{{ forloop|delay }}">
                            <div class="team-item">
                                <div class="position-relative rounded-top" style="z-index: 1;">
                                    <img class="img-fluid rounded-top w-100" src="{{ dr.img.url }}"
                                         alt="">
                                    <div class="position-absolute top-100 start-50 translate-middle bg-light rounded p-2 d-flex">
                                        <a class="btn btn-primary btn-square m-1" href="{{ dr.telegram }}"><i
                                                class="fab fa-telegram fw-normal"></i></a>
                                        <a class="btn btn-primary btn-square m-1" href="{{ dr.linkedin }}"><i
                                                class="fab fa-linkedin-in fw-normal"></i></a>
                                        <a class="btn btn-primary btn-square m-1" href="{{ dr.instagram }}"><i
                                                class="fab fa-instagram fw-normal"></i></a>
                                    </div>
                                </div>
                                <div class="team-text position-relative bg-light text-center rounded-bottom p-4 pt-5">
                                    <h4 class="mb-2">Dr. {{ dr.name }} {{ dr.last_name }}</h4>
                                    <p class="text-primary mb-0">{{ dr.expert }}</p>
                                    <p class="text-primary mb-0">in time: {{ dr.in_time }}- out
                                        time {{ dr.out_time }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            {% else %}
                <div class="col-lg-12 wow slideInUp" data-wow-delay="0.1s">
                    <div class="section-title bg-light rounded h-100 p-5">
                        <h1 class="display-6 mb-4">NOT FOUND DOCTOR</h1>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

doctor/templates/doctor/service_price.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}
    <!-- Pricing Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-5">
                    <div class="section-title mb-4">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Services with
                            Pricing Plan</h5>
                        <h1 class="display-5 mb-0">We Offer Fair Prices for Dental Treatment</h1>
                    </div>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam
                        amet
                        diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus
                        clita
                        duo justo eirmod magna dolore erat amet</p>
                    <h5 class="text-uppercase text-primary wow fadeInUp" data-wow-delay="0.3s">Call for Appointment</h5>
                    <h1 class="wow fadeInUp" data-wow-delay="0.6s">{{ address.phone }}</h1>
                </div>
                <div class="col-lg-7">
                    <div class="owl-carousel price-carousel wow zoomIn" data-wow-delay="0.9s">
                        {% for serv in service %}
                            <div class="price-item pb-4">
                                <div class="position-relative">
                                    <img class="img-fluid rounded-top" src="{{ serv.image.url }}" alt="">
                                    <div class="d-flex align-items-center justify-content-center bg-light rounded pt-2 px-3 position-absolute top-100 start-50 translate-middle"
                                         style="z-index: 2;">
                                        <h2 class="text-primary m-0">${{ serv.cost }}</h2>
                                    </div>
                                </div>
                                <div class="position-relative text-center bg-light border-bottom border-primary py-5 p-4">
                                    <h4>{{ serv.name }}</h4>
                                    <a href="{% url 'appointment:make-appintment' %}?service={{ serv.slug }}"
                                       class="btn btn-primary py-2 px-4 position-absolute top-100 start-50 translate-middle">Appointment</a>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pricing End -->
{% endblock %}

doctor/templates/doctor/teams.html
{% extends 'base.html' %}
{% load static %}
{% load handel_delay %}


{% block title %}
    our team
{% endblock %}


{% block content %}
    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-4 wow slideInUp" data-wow-delay="0.1s">
                    <div class="section-title bg-light rounded h-100 p-5">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Dentist</h5>
                        <h1 class="display-6 mb-4">Meet Our Certified & Experienced Dentist</h1>
                        <a href="{% url 'appointment:make-appintment' %}"
                           class="btn btn-primary py-3 px-5">Appointment</a>
                    </div>
                </div>
                {% for dr in doctor %}
                    <div class="col-lg-4 wow slideInUp" data-wow-delay="{{ forloop|delay }}">
                        <div class="team-item">
                            <div class="position-relative rounded-top" style="z-index: 1;">
                                <img class="img-fluid rounded-top w-100" src="{{ dr.img.url }}"
                                     alt="">
                                <div class="position-absolute top-100 start-50 translate-middle bg-light rounded p-2 d-flex">
                                    <a class="btn btn-primary btn-square m-1" href="{{ dr.telegram }}"><i
                                            class="fab fa-telegram fw-normal"></i></a>
                                    <a class="btn btn-primary btn-square m-1" href="{{ dr.linkedin }}"><i
                                            class="fab fa-linkedin-in fw-normal"></i></a>
                                    <a class="btn btn-primary btn-square m-1" href="{{ dr.instagram }}"><i
                                            class="fab fa-instagram fw-normal"></i></a>
                                </div>
                            </div>
                            <div class="team-text position-relative bg-light text-center rounded-bottom p-4 pt-5 align-items-center align-content-center">
                                <h4 class="mb-2"><a class="text-dark" href="{% url 'doctor:doctor-detail' dr.id %}">
                                    Dr. {{ dr.name }} {{ dr.last_name }}
                                </a></h4>
                                <p class="text-primary mb-0">{{ dr.expert }}</p>
                                <p class="text-primary mb-0">in time: {{ dr.in_time }}- out time {{ dr.out_time }}
                                </p>
                                <!-- star rating -->
                             <span class="fa fa-star {% if 1 <= dr.id|rate %}checked{% endif %}"></span>
                                    <span class="fa fa-star {% if 2 <= dr.id|rate %}checked{% endif %}"></span>
                                    <span class="fa fa-star {% if 3 <= dr.id|rate %}checked{% endif %}"></span>
                                    <span class="fa fa-star {% if 4 <= dr.id|rate %}checked{% endif %}"></span>
                                    <span class="fa fa-star {% if 5 <= dr.id|rate %}checked{% endif %}"></span>
                                <!-- star rating end-->
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/rating.js' %}"></script>
    <!-- Team End -->

{% endblock %}