about/urls.py
from django.urls import path
from .views import About

app_name = 'about'
urlpatterns = [
    path('', About.as_view(), name='about-use' )
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),
    path('log-out/', views.LogOut.as_view(), name='log-out'),
    path('register', views.CheckToken.as_view(), name='register'),
    path('set-info', views.SetInfoView.as_view(), name='set-info'),
    path('sign-in/', views.SignIn.as_view(), name='sign-in'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.ChangePassword.as_view(), name='change-password'),
    path('forget-password/', views.ForgetPassword.as_view(), name='forget-password'),
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.Blog.as_view (), name='blogs'),
    path('detail/<int:pk>', views.BlogDetail.as_view (), name='blog_detail'),
]

dental_appointment/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('appintment/', include('appointment.urls')),
    path('doctor/', include('doctor.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('account.urls')),
    path('rating/', include('rating.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path, include
from . import views

app_name = 'doctor'
urlpatterns = [
    path('search-doctor', views.SearchDoctor.as_view(), name='search-doctor'),
    path('service-price', views.ServicesAndPrices.as_view(), name='service-price'),
    path('doctors-certificate', views.DoctorsCertificate.as_view(), name='doctors-certificate'),
    path('our-team', views.Team.as_view(), name='our-team'),
    path('doctor-detail/<int:pk>/', views.doctor_detail, name='doctor-detail'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

templates/includes/footer_part.html
{% load static%}
<!-- Newsletter Start -->
<div class="container-fluid position-relative pt-5 wow fadeInUp" data-wow-delay="0.1s" style="z-index: 1;">
    <div class="container">
    </div>
</div>
<!-- Newsletter End -->


<!-- Footer Start -->
<div class="container-fluid bg-dark text-light py-5 wow fadeInUp" data-wow-delay="0.3s" style="margin-top: -75px;">
    <div class="container pt-5">
        <div class="row g-5 pt-4">
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Popular Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-light mb-2" href="{% url 'home:home' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-light mb-2" href="{% url 'about:about-use' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-light mb-2" href="{% url 'doctor:service-price' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest
                        Blog</a>
                    <a class="text-light" href="{% url 'contact:contact-us' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i
                        class="bi bi-geo-alt text-primary me-2"></i>{{ address.state }}-{{ address.city_name }}
                <p>{{ address.rest_add }}</p></p>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>{{ address.email }}</p>
                <p class="mb-0"><i class="fas fa-phone me-2"></i>{{ address.phone }}</p>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div class="d-flex">
                    <a class="btn btn-primary btn-square m-1" href="{{ address.telegram }}"><i
                            class="fab fa-telegram fw-normal"></i></a>
                    <a class="btn btn-primary btn-square m-1" href="{{ address.linkedin }}"><i
                            class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-primary btn-square m-1" href="{{ address.instagram }}"><i
                            class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid text-light py-4" style="background: #051225;">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-12 text-center text-md-start">
                <p class="mb-md-0">&copy; <a class="text-white border-bottom" href="{% url 'home:home' %}">DentCare</a>.
                    All Rights
                    Reserved.</p>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>

templates/includes/full_screen.html
<!-- Full Screen Search Start -->
<div class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content" style="background: rgba(9, 30, 62, .7);">
            <div class="modal-header border-0">
                <button type="button" class="btn bg-info btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                <div class="input-group" style="max-width: 600px;">
                    <input type="text" class="form-control bg-transparent border-primary p-3"
                           placeholder="Type search keyword">
                    <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Full Screen Search End -->

templates/includes/loding_bars.html
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-dark m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->

templates/includes/scrip_importance.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'lib/twentytwenty/jquery.event.move.js' %}"></script>
<script src="{% static 'lib/twentytwenty/jquery.twentytwenty.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"></script>


<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

templates/includes/stylesheet_links.html
{% load static %}
<meta charset="utf-8">

<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Free HTML Templates" name="keywords">
<meta content="Free HTML Templates" name="description">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap"
      rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">


<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

<!-- Libraries Stylesheet -->
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>
<link href="{% static 'lib/twentytwenty/twentytwenty.css' %}" rel="stylesheet"/>

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Template Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

templates/includes/topbar_navbar.html
<!-- Topbar Start -->
<div class="container-fluid bg-light ps-5 pe-0 d-none d-lg-block">
    <div class="row gx-0">
        <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
        </div>
        <div class="col-md-6 text-center text-lg-end">
            <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                <div class="me-3 pe-3 border-end py-2">
                    <p class="m-0"><i class="fa fa-envelope-open me-2"></i>{{ address.email }}</p>
                </div>
                <div class="py-2">
                    <p class="m-0"><i class="fa fa-phone-alt me-2"></i>{{ address.phone }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
    <a href="{% url 'home:home' %}" class="navbar-brand p-0">
        <h1 class="m-0 text-primary"><i class='fas fa-tooth me-2'></i>DentCare</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-0">
            <a href="{% url 'home:home' %}" class="nav-item nav-link active text-dark">Home</a>
            <a href="{% url 'blog:blogs' %}" class="nav-item nav-link">Blogs</a>
            <a href="{% url 'about:about-use' %}" class="nav-item nav-link">About</a>
            <a href="{% url 'doctor:service-price' %}" class="nav-item nav-link">Service & Pricing</a>

            <a href="{% url 'contact:contact-us' %}" class="nav-item nav-link">Contact</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu m-0">
                    <a href="{% url 'doctor:our-team' %}" class="dropdown-item">Our Dentist</a>
                    <a href="{% url 'doctor:doctors-certificate' %}" class="dropdown-item">Certificate</a>
                </div>
            </div>

            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle bg-light" data-bs-toggle="dropdown">
                    <span class="">account</span>
                </a>
                <div class="dropdown-menu m-0">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'account:sign-up' %}" class="dropdown-item">sign up</a>
                        <a href="{% url 'account:sign-in' %}" class="dropdown-item">sign in</a>
                        <a href="{% url 'account:forget-password' %}" class="dropdown-item">forget password</a>
                    {% else %}
                        <a href="{% url 'account:profile' %}" class="dropdown-item">profile</a>
                        <a href="{% url 'account:change-password' %}" class="dropdown-item">change password</a>
                        <a href="{% url 'account:log-out' %}" class="dropdown-item">log out</a>
                    {% endif %}
                </div>
            </div>


        </div>
        <a href="{% url 'appointment:make-appintment' %}" class="btn btn-primary py-2 px-4 ms-3">Appointment</a>
    </div>
</nav>
<!-- Navbar End -->