blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.Blog.as_view (), name='blogs'),
    path('detail/<int:pk>', views.BlogDetail.as_view (), name='blog_detail'),
]

dental_appointment/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('appintment/', include('appointment.urls')),
    path('doctor/', include('doctor.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('account.urls')),
    path('rating/', include('rating.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from account.models import User
from django.utils.html import mark_safe
from account.models import User
# Create your models here.

class BlogModel(models.Model):
    photo = models.ImageField(upload_to='blogs')
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogs')
    publish_date = models.DateField(auto_now=True)
    text = models.TextField()

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.photo))

    image_tag.short_description = 'Image'
    def __str__(self):
        return self.title

class Visitors(models.Model):
    visitors = models.ForeignKey(User, on_delete=models.CASCADE, related_name='visit')
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, related_name='visited')

    def __str__(self):
        return self.visitors.name + ' - ' + self.visitors.last_name + ': ' + self.blog.title

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from .models import BlogModel, Visitors



class Blog(ListView):
    template_name = 'blog/blogs.html'
    paginate_by = 1
    context_object_name = 'blogs'
    model = BlogModel

class BlogDetail(DetailView):
    model = BlogModel
    template_name = 'blog/blog_detail.html'
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):

        context = super(BlogDetail, self).get_context_data()
        obj = self.object

        if not Visitors.objects.filter(visitors=self.request.user, blog=obj):
            Visitors.objects.create(visitors=self.request.user, blog=obj)
        return context

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% load handel_delay %}
{% load paginate_in_result %}
{% block title %}{{ blog.name }}{% endblock title %}

{% block content %}
    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-12 wow slideInUp" data-wow-delay="0.1s">
                    <div class="team-item">
                        <div class="team-text position-relative bg-light text-center rounded-bottom p-4 pt-5">
                            <img class="img-fluid rounded-top w-50" src="{{ blog.photo.url }}"
                                 alt="">
                            <h4 class="mb-2"><a class="text-dark" href="#">
                                {{ blog.title }}
                            </a></h4>
                            <p class="text-primary mb-0">
                            <div class="row m-2">
                                <div class="col-lg-6 col-sm-12">
                                    <p>
                                        <i class="bi bi-person me-1"></i>{{ blog.user.name }} {{ blog.user.last_name }}
                                    </p>
                                </div>
                                <div class="col-lg-6 col-sm-12">
                                    <p>
                                        <i class="bi bi-calendar me-1"></i>{{ blog.publish_date }}
                                    </p>
                                </div>
                            </div>
                            </p>
                            <hr>
                            <p class="text-dark mb-2">{{ blog.text }}</p>
                            <hr>
                            <div class="text-start">
                                <a href="https://www.facebook.com/sharer.php?u={{ request.build_absolute_uri }}" class="facebook-btn">
                                    <i class="fab fa-facebook-square m-2 " style="color: #1877f2" size="40"></i>
                                </a>
                                <a target="_blank" href="https://api.whatsapp.com/send?text={{ blog.title }} {{ request.build_absolute_uri }}">
                                    <i class="fab fa-whatsapp m-2 " style="color: limegreen"></i>
                                </a>
                                <a href="https://twitter.com/share?url={{ request.build_absolute_uri }}&text={{ blog.title }}" class="twitter-btn">
                                    <i class="fab fa-twitter-square m-2 " style="color: dodgerblue"></i>
                                </a>
                                <a href="https://pinterest.com/pin/create/bookmarklet/?media={{ blog.photo }}&url={{ request.build_absolute_uri }}&description={{ blog.title }}" class="pinterest-btn">
                                    <i class="fa fa-pinterest-square m-2 " style="color: firebrick"></i>
                                </a>
                                <a href="https://www.linkedin.com/shareArticle?url={{ request.build_absolute_uri }}&title={{ blog.title }}" class="linkedin-btn">
                                    <i class="fa fa-linkedin-square m-2 " style="color: steelblue"></i>
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->
{% endblock content %}

blog/templates/blog/blogs.html
{% extends 'base.html' %}
{% load static %}
{% load handel_delay %}
{% load paginate_in_result %}
{% block title %}Blogs{% endblock title %}

{% block content %}
    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-12 wow slideInUp" data-wow-delay="0.1s">
                    <div class="section-title rounded h-100">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Blogs</h5>
                    </div>
                </div>
                {% for bl in blogs %}
                    <div class="col-lg-6 wow slideInUp" data-wow-delay="{{ forloop|delay }}">
                        <div class="team-item">
                            <div class="position-relative rounded-top" style="z-index: 1;">
                                <a href="{% url 'blog:blog_detail' bl.id %}">
                                    <img class="img-fluid rounded-top w-100" src="{{ bl.photo.url }}"
                                         alt="">
                                </a>
                            </div>
                            <div class="team-text position-relative bg-light text-center rounded-bottom p-4 pt-5">
                                <h4 class="mb-2"><a class="text-dark" href="{% url 'blog:blog_detail' bl.id %}">
                                    {{ bl.title }}
                                </a></h4>

                                <p class="text-dark mb-2">{{ bl.text|slice:":100" }} <a href="{% url 'blog:blog_detail' bl.id %}">...</a></p>
                                <p class="text-primary mb-0">
                                <div class="row m-2">
                                    <div class="col-lg-6 col-sm-12">
                                        <p>
                                            <i class="bi bi-person me-1"></i>{{ bl.user.name }} {{ bl.user.last_name }}
                                        </p>
                                    </div>
                                    <div class="col-lg-6 col-sm-12">
                                       <span class="text-dark me-1">
                                           <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                               <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                               <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                           </svg>
                                       </span>
                                        {{ bl.visited.count }}</div>
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-12">
                    <nav>
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% param_replace page=1 %}">First</a>
                                </li>
                                {% if page_obj.previous_page_number != 1 %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                                    </li>
                                {% endif %}
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <li class="page-item">
                                        <a class="page-link" href="?{% param_replace page=num %}">{{ num }}</a>
                                    </li>
                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                    <li class="page-item">
                                        <a class="page-link" href="?{% param_replace page=num %}">{{ num }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                {% if page_obj.next_page_number != paginator.num_pages %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a class="page-link"
                                       href="?{% param_replace page=page_obj.paginator.num_pages %}">Last</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->
{% endblock content %}